### ISSUE TITLE
Couldn't download the models

### ISSUE THREAD

**Issue by CrackerHax** [HighCWu/starganv2vc-paddle#1]
Download link on the page didn't do anything. You need drop baidu and get a a better host.

**Comment by HighCWu** [comment]
Perhaps you're right. Links can be used to download weights on huggingface spaces, but I can't confirm whether other areas can be accessed normally. I don't have enough other drive space to host the weights at the moment. If you are eager to try running it locally, you can directly use the official weights of stargan2-vc. The weights used in this repo are also converted from there

**Comment by CrackerHax** [comment]
I think the link might be bad because I am in the USA.

I tried using the Stargan2-VC models and they didn't work.

**Comment by HighCWu** [comment]
I could run the official repo. Maybe you just need to spend more time to config the it. I'll try to upload weights to huggingface if I have time, then you could have a try.

**Comment by HighCWu** [comment]
@CrackerHax You can download model [here](https://huggingface.co/HighCWu/starganv2vc-paddle) now.
